### 회원가입
POST http://localhost:3002/api/auth/signup
Content-Type: application/json

{
  "email": "testuser2@example.com",
  "password": "testpassword",
  "passwordConfirmation": "testpassword",
  "nickname": "테스트유저2"
}

### 로그인
POST http://localhost:3002/api/auth/login
Content-Type: application/json

{
  "email": "testuser2@example.com",
  "password": "testpassword"
}
### 랜덤 상자 뽑기 (포인트 획득)
POST http://localhost:3002/api/points/random-box
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxZjU3NzlhZi00NmU3LTQ0NjgtODg5NS1lNTRlYTkyOGIwYTEiLCJlbWFpbCI6InRlc3R1c2VyMkBleGFtcGxlLmNvbSIsIm5pY2tuYW1lIjoi7YWM7Iqk7Yq47Jyg7KCAMiIsImlhdCI6MTc0Nzk3ODA2NSwiZXhwIjoxNzQ3OTc4OTY1fQ.YrGANRr_itd2_13r3L_jgCXjCRxHwvj8qaq3JF_2CgE
Content-Type: application/json

### 내 포인트 조회
GET http://localhost:3002/api/points/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxZjU3NzlhZi00NmU3LTQ0NjgtODg5NS1lNTRlYTkyOGIwYTEiLCJlbWFpbCI6InRlc3R1c2VyMkBleGFtcGxlLmNvbSIsIm5pY2tuYW1lIjoi7YWM7Iqk7Yq47Jyg7KCAMiIsImlhdCI6MTc0Nzk3ODA2NSwiZXhwIjoxNzQ3OTc4OTY1fQ.YrGANRr_itd2_13r3L_jgCXjCRxHwvj8qaq3JF_2CgE